# Generated by Django 4.0.3 on 2022-04-19 07:32

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='tag'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='title'),
        ),
    ]
