# Generated by Django 4.0.3 on 2022-04-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tag_slug_alter_todo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='slug',
        ),
    ]
