# Generated by Django 4.0.3 on 2022-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_tag_slug_remove_todo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.CharField(choices=[('health', 'Health'), ('work', 'Work'), ('home', 'Home'), ('social', 'Social'), ('outdoor', 'Outdoor'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
